# -*- coding: utf-8 -*-
"""AI: ML Dimensionality (CountryData).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b7QYiq1diJz1euSLRWW7Z2UwBOB3yz91
"""

# Imports
import numpy as np
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd

# Data
dataFile = "//content//drive//MyDrive//Coding//Personal Projects//1: Artificial Intelligence//Resources//CountryData.csv"
data = pd.read_csv(dataFile)
dataset = data.values.tolist()

allCountriesData = []

for row in dataset:
  countryData = []
  for column in range(1,len(row)): # no need to include country name, start at col 1
    countryData.append(eval(str(row[column])))
  allCountriesData.append(countryData) # 48 components per country

# PCA Analysis: 48 Components to 2 Components
model = PCA(n_components = 48)
model.fit(allCountriesData)
X = model.transform(allCountriesData)

# Scree Plot
fig_1 = plt.figure(figsize = (6,6))
labels = []
barHeight = []
for i in range(len(model.explained_variance_ratio_)):
  labels.append("PC" + str(i + 1))
  barHeight.append(model.explained_variance_ratio_[i])
plt.bar(labels, barHeight, align='center', color = 'red')

# Transformed Dataset
fig = plt.figure(figsize=(10,10))
ax = fig.gca()
ax.set_aspect('equal')
plt.scatter(X[:,0], X[:,1], marker = "o", color = "orange") # First two PCs correspond to groupings the most
plt.scatter(0, 0, marker = "o", s = 200, edgecolors = 'k', color = "red", linewidths = 2, label = "dataset mean")

plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend()